Repository ChatGPTNextWeb/NextChat, pull requests merged in 2024-07, with the labels that each got.

#4906 gemini using real sse format response #3677 #3688
  app/api/google/[...path]/route.ts
  app/client/platforms/google.ts
Labels: planned

#4917 feat: using fetch to get buildin masks
  app/masks/build.ts
  app/masks/index.ts
  package.json
  yarn.lock
Labels: help wanted

#4923 Refactor model table
  app/api/anthropic/[...path]/route.ts
  app/api/common.ts
  app/store/config.ts
  app/utils/model.ts
Labels: enhancement, planned

#4930 support azure deployment name
  app/api/auth.ts
  app/api/azure/[...path]/route.ts
  app/api/common.ts
  app/azure.ts
  app/client/api.ts
  app/client/platforms/openai.ts
  app/components/chat.tsx
  app/components/exporter.tsx
  app/components/home.tsx
  app/components/model-config.tsx
  app/constant.ts
  app/store/access.ts
  app/store/chat.ts
  app/store/config.ts
  app/utils/checkers.ts
  app/utils/hooks.ts
  next.config.mjs
Labels: planned

#4974 hotfix: doubao display name
  app/utils/model.ts
Labels: bug

#4984 chore: add chinese template
  .github/ISSUE_TEMPLATE/1_bug_report.yml
  .github/ISSUE_TEMPLATE/1_bug_report_cn.yml
  .github/ISSUE_TEMPLATE/2_feature_request.yml
  .github/ISSUE_TEMPLATE/2_feature_request_cn.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, question

#5061 using cache storage store image data #5013
  app/client/platforms/alibaba.ts
  app/client/platforms/anthropic.ts
  app/client/platforms/google.ts
  app/client/platforms/openai.ts
  app/components/chat.tsx
  app/constant.ts
  app/utils/chat.ts
  public/serviceWorker.js
  public/serviceWorkerRegister.js
Labels: enhancement

#4847 add google api safety settings by Settings page
  app/client/platforms/google.ts
  app/components/settings.tsx
  app/constant.ts
  app/locales/cn.ts
  app/locales/en.ts
  app/store/access.ts
Labels: planned

#4983 [Feature] Stable Diffusion
  .gitignore
  README.md
  README_CN.md
  app/api/auth.ts
  app/api/stability/[...path]/route.ts
  app/api/webdav/[...path]/route.ts
  app/client/api.ts
  app/components/button.tsx
  app/components/chat.tsx
  app/components/error.tsx
  app/components/home.tsx
  app/components/sd/index.tsx
  app/components/sd/sd-panel.module.scss
  app/components/sd/sd-panel.tsx
  app/components/sd/sd-sidebar.tsx
  app/components/sd/sd.module.scss
  app/components/sd/sd.tsx
  app/components/settings.tsx
  app/components/sidebar.tsx
  app/components/ui-lib.module.scss
  app/components/ui-lib.tsx
  app/config/client.ts
  app/config/server.ts
  app/constant.ts
  app/icons/discovery.svg
  app/icons/history.svg
  app/icons/sd.svg
  app/layout.tsx
  app/locales/cn.ts
  app/locales/en.ts
  app/locales/tw.ts
  app/store/access.ts
  app/store/sd.ts
  app/utils/chat.ts
  public/serviceWorker.js
Labels: planned
